analyze:
    async: true
    mode: deep
    create-group: true
    solc: 0.6.8
    check-properties: true
    targets:
        - mythx/MythXVerifySimpleProperties.sol:MythXVerifySimpleProperties
        - mythx/MythXVerifySignatureValidation01.sol:MythXVerifySignatureValidation01
        - mythx/MythXVerifySignatureValidation02.sol:MythXVerifySignatureValidation02
